'use strict'
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs/promises'); const os = require('node:os'); const path = require('node:path')
const { createBackupManager } = require('../preload/backupManager')
test('exports redacted backups and imports with recoverable file backups', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-backup-test-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const dataDir = path.join(root, 'data'); await fs.mkdir(dataDir); await fs.writeFile(path.join(dataDir, 'providers.json'), JSON.stringify({ providers: [{ apiKey: 'secret', name: 'P' }] }))
  await fs.writeFile(path.join(dataDir, 'omo-profiles.json'), JSON.stringify({ current: { standard: 'omo-1' }, profiles: [{ id: 'omo-1', name: 'Research' }] }))
  const manager = createBackupManager({ dataDir }); const destination = path.join(root, 'backup.json'); await manager.exportBackup(destination, { includeSecrets: false, includeLogs: false })
  const bundle = JSON.parse(await fs.readFile(destination, 'utf8')); assert.equal(JSON.parse(bundle.files['providers.json']).providers[0].apiKey, '')
  assert.equal(JSON.parse(bundle.files['omo-profiles.json']).profiles[0].name, 'Research')
  const withSecret = path.join(root, 'secret.json'); await manager.exportBackup(withSecret, { includeSecrets: true }); await fs.writeFile(path.join(dataDir, 'providers.json'), '{}')
  await fs.writeFile(path.join(dataDir, 'omo-profiles.json'), '{}')
  const result = await manager.importBackup(withSecret); assert.ok(result.imported >= 2); assert.equal(JSON.parse(await fs.readFile(path.join(dataDir, 'providers.json'), 'utf8')).providers[0].apiKey, 'secret')
  assert.equal(JSON.parse(await fs.readFile(path.join(dataDir, 'omo-profiles.json'), 'utf8')).profiles[0].id, 'omo-1')
  const entries = await fs.readdir(dataDir); assert.ok(entries.some((name) => name.includes('.pre-import-')))
})

test('本地数据快照支持策略、重命名、恢复安全备份与删除', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'cc-local-backup-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const dataDir = path.join(root, 'data'); await fs.mkdir(dataDir, { recursive: true })
  await fs.writeFile(path.join(dataDir, 'providers.json'), JSON.stringify({ value: 1 }))
  const manager = createBackupManager({ dataDir })
  assert.deepEqual(await manager.saveLocalBackupSettings({ intervalHours: 6, retainCount: 3 }), { intervalHours: 6, retainCount: 3 })
  const created = await manager.createLocalBackup()
  assert.match(created.filename, /^db_backup_.*\.snapshot\.json$/)
  await fs.writeFile(path.join(dataDir, 'providers.json'), JSON.stringify({ value: 2 }))
  const renamed = await manager.renameLocalBackup(created.filename, 'baseline')
  const restored = await manager.restoreLocalBackup(renamed)
  assert.equal(JSON.parse(await fs.readFile(path.join(dataDir, 'providers.json'), 'utf8')).value, 1)
  assert.match(restored.safetyBackup, /^safety_before_restore_/)
  assert.equal((await manager.periodicLocalBackupIfNeeded()).created, false)
  await manager.deleteLocalBackup(renamed)
  assert.ok(!(await manager.listLocalBackups()).some((item) => item.filename === renamed))
  await assert.rejects(() => manager.deleteLocalBackup('../bad.snapshot.json'), /无效/)
})

test('导入后半程失败时回滚所有已修改文件并删除本次新建文件', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'cc-backup-rollback-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const dataDir = path.join(root, 'data'); await fs.mkdir(dataDir)
  await fs.writeFile(path.join(dataDir, 'providers.json'), '{"before":true}\n')
  const source = path.join(root, 'backup.json')
  await fs.writeFile(source, JSON.stringify({ format: 'ztools-cc-switch-backup', version: 1, files: { 'providers.json': '{"after":true}\n', 'profiles.json': '{"new":true}\n', 'skills-state.json': '{"fail":true}\n' } }))
  const manager = createBackupManager({ dataDir, beforeImportWrite: ({ index }) => { if (index === 2) throw new Error('simulated disk failure') } })
  await assert.rejects(() => manager.importBackup(source), /已恢复原数据/)
  assert.equal(await fs.readFile(path.join(dataDir, 'providers.json'), 'utf8'), '{"before":true}\n')
  await assert.rejects(fs.access(path.join(dataDir, 'profiles.json')))
  await assert.rejects(fs.access(path.join(dataDir, 'skills-state.json')))
})
