'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')

test('installable manifest always opens the bundled UI', () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(root, 'dist', 'plugin.json'), 'utf8'))

  assert.equal(manifest.main, 'index.html')
  assert.equal(manifest.development, undefined)
  assert.equal(fs.existsSync(path.join(root, 'dist', manifest.main)), true)
  const credentialModule = path.join(root, 'dist', 'preload', 'core', 'credential-storage.js')
  assert.equal(fs.existsSync(credentialModule), true)
  assert.equal(typeof require(credentialModule).createCredentialStorage, 'function')
})

test('QR pairing links drive automatic mobile connection while direct links remain manual', () => {
  const preload = fs.readFileSync(path.join(root, 'public', 'preload', 'services.js'), 'utf8')
  const mobile = fs.readFileSync(path.join(root, 'public', 'web', 'index.html'), 'utf8')
  const mobileApp = fs.readFileSync(path.join(root, 'public', 'web', 'app.js'), 'utf8')

  assert.match(preload, /\?pairing=\$\{encodeURIComponent\(pairing\.sessionId\)\}#pair=\$\{encodeURIComponent\(pairing\.secret\)\}&code=\$\{encodeURIComponent\(pairing\.qrCode\)\}&auto=1/)
  assert.match(preload, /onPairingExpired/)
  assert.match(mobile, /<script src="\/app\.js"><\/script>/)
  assert.match(mobile, /id="autoPairPanel"/)
  assert.match(mobile, /id="manualPairButton"/)
  assert.match(mobile, /id="retryChatButton"/)
  assert.match(mobileApp, /async function loadPairing\(\)/)
  assert.match(mobileApp, /await loadPairing\(\)/)
  assert.match(mobileApp, /window\.addEventListener\(["']hashchange["'],\s*refreshPairing\)/)
  assert.match(mobileApp, /requestedSessionId\s*!==\s*latestPairing\.sessionId/)
  assert.match(mobileApp, /autoCode:\s*fragment\.get\(["']code["']\)/)
  assert.match(mobileApp, /automatic:\s*fragment\.get\(["']auto["']\)\s*===\s*["']1["']/)
  const timing = mobileApp.match(/const AUTO_PAIR_TIMING = Object\.freeze\(\{\s*recognitionHold:\s*(\d+),\s*digitInterval:\s*(\d+),\s*verificationMinimum:\s*(\d+),\s*successHold:\s*(\d+)\s*\}\)/)
  assert.ok(timing, 'automatic pairing timing should be explicit and reviewable')
  assert.ok(Number(timing[1]) >= 400, 'computer recognition should remain visible')
  assert.ok(Number(timing[2]) >= 90, 'code digits should be readable while appearing')
  assert.ok(Number(timing[3]) >= 600, 'connection verification should remain visible')
  assert.ok(Number(timing[4]) >= 800, 'success state should remain visible before entering chat')
  assert.match(mobileApp, /pause\(AUTO_PAIR_TIMING\.verificationMinimum\)/)
  assert.match(mobileApp, /mode\s*=\s*["']manual["']/)
  assert.match(mobileApp, /mode\s*=\s*["']qr["']/)
  assert.match(mobileApp, /history\.replaceState/)
  assert.match(mobileApp, /scannedPairingContext\s*=\s*void 0/)
  assert.match(mobileApp, /showPairedRecovery/)
  assert.match(mobileApp, /deviceLinkTrustedDevice/)
  assert.match(mobileApp, /\/api\/resume\/challenge/)
  assert.match(preload, /createCredentialStorage/)
  assert.match(preload, /protectCredential:\s*seal/)
})
